#!/bin/sh

set -euf
[ "${DEBUG-}" != true ] || set -x

if ! hash ansible 2>/dev/null; then
  echo "[ERROR] cannot find command ansible" >&2
  exit 1
fi

cd -- "$(dirname -- "$0")/.."

create=false
[ -e host_vars/target_onu/vault ] || create=true

if ! $create && ansible -m assert -a 'that=unsealed' target_onu >/dev/null; then
  echo '[INFO] already unsealed'
  exit 0
fi

# input into vault-id: zte-modem-ops user=$USER
# when create new vault file, try to use the saved password
if ! $create || ! vault-keyring-client >/dev/null; then
  vault-keyring-client --set
fi

if $create; then
  EDITOR='tee' ansible-vault create --skip-tty-check host_vars/target_onu/vault >/dev/null <<-END
	unsealed: True
	END
elif ansible -m assert -a 'that=unsealed' target_onu >/dev/null; then
  # check again
  echo '[INFO] unseal successfully'
else
  echo '[ERROR] password in zte-modem-ops is incorrect!' >&2
  exit 1
fi
